pipeline {
   agent any
   
   stages{
       stage("first"){
          when {
             changeset "MYLAB/hotfix/**"
          }
          steps{
            script{
                sh 'echo "hotfix env"'
            }
          }
       }
   }
}
#
