pipeline {
   agent any
   
   stages{
       stage("first"){
          when {
             changeset "MYLAB/hotfix/**"
          }
          steps{
            script{
                sh 'echo "hotfix"'
            }
          }
       }
   }
}
def checkFileChanges(directory) {
    // Run git diff command and capture the output
    def diffOutput = sh(script: "git diff --name-only HEAD HEAD~1", returnStdout: true).trim()
    
    // Check if the provided directory is in the output
    return diffOutput.contains(directory)
}
