pipeline {
   agent any
   
   stages{
       stage("first"){
            when { 
               expression { BRANCH_NAME == 'dev' }
            }   
            steps{
               script{
                   sh 'echo "QA env"'
                   sh 'uptime'
               }
            }
       }
   }
}

