pipeline {
   agent any
   
   stages{
       stage("first"){
          when {
             changeset "MYLAB/QA/**"
          }
          steps{
            script{
                sh 'echo "QA env"'
                sh 'uptime'
            }
          }
       }
   }
}

