pipeline {
   agent any
   environment {
        
        BRANCH_NAME = "dev"
   }
   stages{
       stage("first"){
            steps{
               script{
                    def fileChanges = sh(script: 'git diff --name-only', returnStdout: true).trim()
                    echo "Changed files: ${fileChanges}"
                   sh 'uptime'
               }
            }
       }
   }
}

