pipeline {
   agent any
   
   stages{
       stage("first"){
          when {
                // Check if changes were made to the specified folder
                changeset "MYLAB/prod/**"
          }
          steps{
            script{
                sh 'uptime'
            }
          }
       }
   }
}
