pipeline {
   agent any
   
   stages{
       stage("first"){
          steps{
            script{
                sh 'echo "QA"'
                sh 'uptime'
            }
          }
       }
   }
}
